using UnityEngine;
using UnityEngine.UI;
using AlicizaX.UI.Runtime;
namespace Game.UI
{
	[UIRes(ui_UILogicTestAlert.ResTag, EUIResLoadType.AssetBundle)]
	public class ui_UILogicTestAlert : UIHolderObjectBase
	{
		public const string ResTag = "UILogicTestAlert";
		#region Generated by Script Tool

		[SerializeField]
		private UXButton mBtnEscTest;
		public UXButton BtnEscTest => mBtnEscTest;

		[SerializeField]
		private UXButton mBtnGTest;
		public UXButton BtnGTest => mBtnGTest;

		#endregion


	}
}
