using TMPro;
using UnityEngine;
using UnityEngine.UI;
using AlicizaX.UI.Runtime;
namespace Game.UI
{
	[UIRes(ui_UIHomeWindow.ResTag, EUIResLoadType.AssetBundle)]
	public class ui_UIHomeWindow : UIHolderObjectBase
	{
		public const string ResTag = "UIHomeWindow";
		#region Generated by Script Tool

		[SerializeField]
		private UXButton mBtnBag;
		public UXButton BtnBag => mBtnBag;

		[SerializeField]
		private UXButton mBtnExit;
		public UXButton BtnExit => mBtnExit;

		[SerializeField]
		private UXButton mBtnRole;
		public UXButton BtnRole => mBtnRole;

		[SerializeField]
		private UXButton mBtnShop;
		public UXButton BtnShop => mBtnShop;

		[SerializeField]
		private UXButton mBtnTestTips;
		public UXButton BtnTestTips => mBtnTestTips;

		[SerializeField]
		private Image mImgBackGround;
		public Image ImgBackGround => mImgBackGround;

		[SerializeField]
		private Image mImgNoticePanel;
		public Image ImgNoticePanel => mImgNoticePanel;

		[SerializeField]
		private Image mImgTopButtonPanel;
		public Image ImgTopButtonPanel => mImgTopButtonPanel;

		[SerializeField]
		private TextMeshProUGUI mTextNoticeContent;
		public TextMeshProUGUI TextNoticeContent => mTextNoticeContent;

		[SerializeField]
		private TextMeshProUGUI mTextNoticeTitle;
		public TextMeshProUGUI TextNoticeTitle => mTextNoticeTitle;

		#endregion


	}
}
