using AlicizaX.UI;
using UnityEngine;
using UnityEngine.UI;
using AlicizaX.UI.Runtime;
namespace Game.UI
{
	[UIRes(ui_UILoadUpdateWindow.ResTag, EUIResLoadType.AssetBundle)]
	public class ui_UILoadUpdateWindow : UIHolderObjectBase
	{
		public const string ResTag = "UILoadUpdateWindow";
		#region Generated by Script Tool

		[SerializeField]
		private UXButton mBtnETest;
		public UXButton BtnETest => mBtnETest;

		[SerializeField]
		private UXButton mBtnEscTest;
		public UXButton BtnEscTest => mBtnEscTest;

		[SerializeField]
		private UXButton mBtnQTest;
		public UXButton BtnQTest => mBtnQTest;

		[SerializeField]
		private UXButton mBtnTest;
		public UXButton BtnTest => mBtnTest;

		[SerializeField]
		private Image mImgBackGround;
		public Image ImgBackGround => mImgBackGround;

		[SerializeField]
		private RecyclerView mScrollViewTestList;
		public RecyclerView ScrollViewTestList => mScrollViewTestList;

		#endregion

		public UXController.ControllerDefinition CtlLevel { get; private set; }
		public override void Awake()
		{
			base.Awake();
			var ctl = gameObject.GetComponent<UXController>();
			CtlLevel = ctl.GetControllerByName("ctlLevel");
		}

	}
}
