using TMPro;
using UnityEngine;
using UnityEngine.UI;
using AlicizaX.UI.Runtime;
namespace Game.UI
{
	[UIRes(ui_UIBuyAlertWindow.ResTag, EUIResLoadType.AssetBundle)]
	public class ui_UIBuyAlertWindow : UIHolderObjectBase
	{
		public const string ResTag = "UIBuyAlertWindow";
		#region Generated by Script Tool

		[SerializeField]
		private UXButton mBtnClose;
		public UXButton BtnClose => mBtnClose;

		[SerializeField]
		private UXButton mBtnConfirm;
		public UXButton BtnConfirm => mBtnConfirm;

		[SerializeField]
		private UXButton mBtnMinus;
		public UXButton BtnMinus => mBtnMinus;

		[SerializeField]
		private UXButton mBtnPlus;
		public UXButton BtnPlus => mBtnPlus;

		[SerializeField]
		private Image mImgBackGround;
		public Image ImgBackGround => mImgBackGround;

		[SerializeField]
		private Image mImgItemIcon;
		public Image ImgItemIcon => mImgItemIcon;

		[SerializeField]
		private Image mImgPanel;
		public Image ImgPanel => mImgPanel;

		[SerializeField]
		private Image mImgQuantityPanel;
		public Image ImgQuantityPanel => mImgQuantityPanel;

		[SerializeField]
		private TMP_InputField mInputQuantity;
		public TMP_InputField InputQuantity => mInputQuantity;

		[SerializeField]
		private TextMeshProUGUI mTextItemName;
		public TextMeshProUGUI TextItemName => mTextItemName;

		[SerializeField]
		private TextMeshProUGUI mTextTitle;
		public TextMeshProUGUI TextTitle => mTextTitle;

		[SerializeField]
		private TextMeshProUGUI mTextTotalPrice;
		public TextMeshProUGUI TextTotalPrice => mTextTotalPrice;

		#endregion


	}
}
