using AlicizaX.UI;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using AlicizaX.UI.Runtime;
namespace Game.UI
{
	[UIRes(ui_UIShopWindow.ResTag, EUIResLoadType.AssetBundle)]
	public class ui_UIShopWindow : UIHolderObjectBase
	{
		public const string ResTag = "UIShopWindow";
		#region Generated by Script Tool

		[SerializeField]
		private UXButton mBtnClose;
		public UXButton BtnClose => mBtnClose;

		[SerializeField]
		private UXToggle mTogItem;
		public UXToggle TogItem => mTogItem;

		[SerializeField]
		private UXToggle mTogPack;
		public UXToggle TogPack => mTogPack;

		[SerializeField]
		private UXToggle mTogRecommend;
		public UXToggle TogRecommend => mTogRecommend;

		[SerializeField]
		private UXToggle mTogSkin;
		public UXToggle TogSkin => mTogSkin;

		[SerializeField]
		private Image mImgBackGround;
		public Image ImgBackGround => mImgBackGround;

		[SerializeField]
		private Image mImgHeaderPanel;
		public Image ImgHeaderPanel => mImgHeaderPanel;

		[SerializeField]
		private Image mImgInfoPanel;
		public Image ImgInfoPanel => mImgInfoPanel;

		[SerializeField]
		private Image mImgListPanel;
		public Image ImgListPanel => mImgListPanel;

		[SerializeField]
		private Image mImgTabPanel;
		public Image ImgTabPanel => mImgTabPanel;

		[SerializeField]
		private RecyclerView mScrollViewGoodsList;
		public RecyclerView ScrollViewGoodsList => mScrollViewGoodsList;

		[SerializeField]
		private TextMeshProUGUI mTextCurrency;
		public TextMeshProUGUI TextCurrency => mTextCurrency;

		[SerializeField]
		private TextMeshProUGUI mTextInfoContent;
		public TextMeshProUGUI TextInfoContent => mTextInfoContent;

		[SerializeField]
		private TextMeshProUGUI mTextInfoTitle;
		public TextMeshProUGUI TextInfoTitle => mTextInfoTitle;

		[SerializeField]
		private TextMeshProUGUI mTextSubTitle;
		public TextMeshProUGUI TextSubTitle => mTextSubTitle;

		[SerializeField]
		private TextMeshProUGUI mTextTitle;
		public TextMeshProUGUI TextTitle => mTextTitle;

		#endregion


	}
}
